// this is header part of program 
// including iostream.h which contains defnitions for input output stream functions like cin , cout
#include<iostream.h>
#include<conio.h>  // console input output ,for using clrscr(), getch() functions 
// main is starting point for any c++ program , program execution start from here
void main() {
clrscr();  // clearing the output screen	
// just printing a message to console output	
cout<<"Hello Welcome to C++";
getch(); // will wait to enter any key before existing the output screen .
}
